

services:

  web-app:
    image: abbasahsan/express-app-ci-cd:latest
    container_name: web-app
    ports:
      - 8080:8080
    
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: web-app
    depends_on:
      - web-app
    