name: Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout to the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: abbasahsan/express-app-ci-cd:latest
